### ISSUE TITLE
Discord Group?

### ISSUE THREAD

**Issue by JinxBR** [ensoulsharp-io/EnsoulSharp.Assemblies#1]
which ensoulsharp discord group?

**Comment by fexolol** [comment]
cria um vc ai e bota todo mundo

**Comment by JinxBR** [comment]
mas ja existe um po, só que eles não divulgam

**Comment by fexolol** [comment]
me add ai no discord luicas#3610

**Comment by fexolol** [comment]
discord group https://discord.gg/4YFQsy

**Comment by snowi3652** [comment]
new discord and update ? 10.3
