### ISSUE TITLE
Scripts more requests!

### ISSUE THREAD

**Issue by JinxBR** [ensoulsharp-io/EnsoulSharp.Assemblies#2]
Ezreal
Caitlyn
Blitzcrank

Graves
Kindred
Rengar
Lucian

Nidalee
Orianna
Lux
Annie

Brand
Vel'Koz
Viktor
Varus
Sivir
Zoe

Ziggs
Camille
Corki
Sylas
Jarvan

**Comment by seskral2662** [comment]
Hİ , How did you run it?

**Comment by JinxBR** [comment]
using hotfix!

**Comment by neverlose47** [comment]
Please add discord xuanman#0953

**Comment by 979685557qwe** [comment]
有Z字号脚本吗

**Comment by qwe522110** [comment]
CN游戏已更新！可否ES更新版本
